export const FETCH_POSTS_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POST_FAILURE';
export const FETCH_GET_POSTS_REQUEST = 'FETCH_GET_POST_REQUEST';
export const FETCH_GET_POSTS_SUCCESS = 'FETCH_GET_POST_SUCCESS';
export const FETCH_GET_POSTS_FAILURE = 'FETCH_GET_POST_FAILURE';

export const FETCH_COMMENT_REQUEST = 'FETCH_COMMENT_REQUEST';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_FAILURE = 'FETCH_COMMENT_FAILURE';
export const FETCH_GET_COMMENT_REQUEST = 'FETCH_GET_COMMENT_REQUEST';
export const FETCH_GET_COMMENT_SUCCESS = 'FETCH_GET_COMMENT_SUCCESS';
export const FETCH_GET_COMMENT_FAILURE = 'FETCH_GET_COMMENT_FAILURE';

export const FETCH_EDIT_POST_REQUEST = 'FETCH_EDIT_POST_REQUEST';
export const FETCH_EDIT_POST_SUCCESS = 'FETCH_EDIT_POST_SUCCESS';
export const FETCH_EDIT_POST_FAILURE = 'FETCH_EDIT_POST_FAILURE';
export const FETCH_GET_EDIT_POST_REQUEST = 'FETCH_GET_EDIT_POST_REQUEST';
export const FETCH_GET_EDIT_POST_SUCCESS = 'FETCH_GET_EDIT_POST_SUCCESS';
export const FETCH_GET_EDIT_POST_FAILURE = 'FETCH_GET_EDIT_POST_FAILURE';
