export const FETCH_POST_PROFILE_REQUEST = 'FETCH_POST_PROFILE_REQUEST';
export const FETCH_POST_PROFILE_SUCCESS = 'FETCH_POST_PROFILE_SUCCESS';
export const FETCH_POST_PROFILE_FAILURE = 'FETCH_POST_PROFILE_FAILURE';

export const FETCH_GET_PROFILE_REQUEST = 'FETCH_GET_PROFILE_REQUEST';
export const FETCH_GET_PROFILE_SUCCESS = 'FETCH_GET_PROFILE_SUCCESS';
export const FETCH_GET_PROFILE_FAILURE = 'FETCH_GET_PROFILE_FAILURE';

export const FETCH_PATCH_PROFILE_REQUEST = 'FETCH_PATCH_PROFILE_REQUEST';
export const FETCH_PATCH_PROFILE_SUCCESS = 'FETCH_PATCH_PROFILE_SUCCESS';
export const FETCH_PATCH_PROFILE_FAILURE = 'FETCH_PATCH_PROFILE_FAILURE';

export const FETCH_GET_USERINFO_REQUEST = 'FETCH_GET_USERINFO_REQUEST';
export const FETCH_GET_USERINFO_SUCCESS = 'FETCH_GET_USERINFO_SUCCESS';
export const FETCH_GET_USERINFO_FAILURE = 'FETCH_GET_USERINFO_FAILURE';
